In [1]:
import numpy as np
import pandas as pd

In [151]:
file = 'C:/Users/singh/Downloads/smol5_has5cropped.csv'
data = pd.read_csv(file)

print(data)

       Make        Model  Index  RawData  ScaleFactor  NumSamples  Duration  \
0       DJI  Inspire1Pro      1      NaN     0.000007     5000000   0.00025   
1       DJI  Inspire1Pro      2      NaN     0.000007     5000000   0.00025   
2       DJI  Inspire1Pro      3      NaN     0.000007     5000000   0.00025   
3       DJI  Inspire1Pro      4      NaN     0.000007     5000000   0.00025   
4       DJI  Inspire1Pro      5      NaN     0.000007     5000000   0.00025   
..      ...          ...    ...      ...          ...         ...       ...   
80  Turnigy           9X      1      NaN     0.000013     5000000   0.00025   
81  Turnigy           9X      2      NaN     0.000013     5000000   0.00025   
82  Turnigy           9X      3      NaN     0.000013     5000000   0.00025   
83  Turnigy           9X      4      NaN     0.000013     5000000   0.00025   
84  Turnigy           9X      5      NaN     0.000013     5000000   0.00025   

             Fs  CroppedData_1  CroppedData_2  ... 

In [4]:
bd = np.transpose(data)
bd = bd.drop(index='Make')
bd = bd.drop(index='RawData')
bd = bd.drop(index='NumSamples')
bd = bd.drop(index='Duration')
bd = bd.drop(index='Fs')
bd = bd.drop(index='Features')
bd = bd.drop(index='ScaleFactor')
bd = bd.drop(index='Model')
bd = bd.drop(index='Index')

In [8]:
print(bd)

                        0      1      2      3      4     5     6     7   \
CroppedData_1          310     22    390   -116    221   291   -82    87   
CroppedData_2          206    -70    374    140    209   107  -110   143   
CroppedData_3          -26    -26     50    272     57  -137  -202   211   
CroppedData_4         -186    -26    -66    228   -147  -253  -214   123   
CroppedData_5          -18   -102    118    220   -279  -301     2    -9   
...                    ...    ...    ...    ...    ...   ...   ...   ...   
CroppedData_999997   -4194  -4734  -3946  -3792  -5023     7   -70  -405   
CroppedData_999998   -1882  -2402  -1594  -1944  -3019  -305  -338  -493   
CroppedData_999999    1462   1458   1650    948    697  -849  -250  -265   
CroppedData_1000000   3894   4086   3674   3108   3901  -861   -70   211   
CroppedData_1000001   3862   4054   3462   3700   4697  -269   130   399   

                        8     9   ...     75      76      77      78      79  \
Cropped

In [9]:
print(bd.columns)

RangeIndex(start=0, stop=85, step=1)


In [5]:
bd1= bd[bd.columns[::5]]
bd2 = bd[bd.columns[1::5]]
bd3 = bd[bd.columns[2::5]]
bd4 = bd[bd.columns[3::5]]
bd5 = bd[bd.columns[4::5]]

print(bd5)

                        4     9      14     19      24     29     34     39  \
CroppedData_1          221   282      0    -15     167    -53     55    118   
CroppedData_2          209    -6     40    -95      75   -121    -29    178   
CroppedData_3           57  -130    -44   -227     -57   -145   -141     38   
CroppedData_4         -147   -46   -292   -107      19   -157   -121   -270   
CroppedData_5         -279   -38   -272    113     159     47     11   -298   
...                    ...   ...    ...    ...     ...    ...    ...    ...   
CroppedData_999997   -5023  -302  -8284  -1303  -18793   9043   3715   4370   
CroppedData_999998   -3019   -54   -600  -2211  -10709   3275   2119   8470   
CroppedData_999999     697   326   7184  -2079    2971  -4097   -853   7906   
CroppedData_1000000   3901   654  10964   -847   14711  -8965  -3309   2590   
CroppedData_1000001   4697   562   8692    949   18587  -8861  -3401  -4538   

                        44      49     54      59  

In [6]:
column_names = ['DJI1', 'DJI2', 'DJI3', 'DJI4', 'DJI5', 'DJI6','DJI7', 'DJI8', 'DJI9', 'DJI10', 'DJI11', 'DJI12', 'DJI13', 'DJI14', 'DJI15', 'DJI16', 'DJI17']
bd1.columns = column_names
bd2.columns = column_names
bd3.columns = column_names
bd4.columns = column_names
bd5.columns = column_names

In [152]:
print(bd1)

                      DJI1  DJI2    DJI3   DJI4    DJI5   DJI6  DJI7  DJI8  \
CroppedData_1          310   291      -9    288   -1054    274  -220   200   
CroppedData_2          206   107      27    584    -602     18    -8   164   
CroppedData_3          -26  -137     391    460     -22     78    52  -172   
CroppedData_4         -186  -253     463     24     -90    282    64  -240   
CroppedData_5          -18  -301     107    -60      30    218   164   -24   
...                    ...   ...     ...    ...     ...    ...   ...   ...   
CroppedData_999997   -4194     7  -10153   -516  -19994  -3982  -424  -476   
CroppedData_999998   -1882  -305  -10213  -1596  -14502   -142  1824  6244   
CroppedData_999999    1462  -849   -4825  -1676    1594   3774  2872  9124   
CroppedData_1000000   3894  -861    2875   -812   13394   5550  2380  6568   
CroppedData_1000001   3862  -269    9399    356   16506   4370   684   432   

                      DJI9   DJI10  DJI11   DJI12  DJI13   DJI1

In [130]:
import matplotlib.pyplot as plt
s10_1 = bd1['DJI10'].values
s10_2 = bd2['DJI10'].values
s10_3 = bd3['DJI10'].values
s10_4 = bd4['DJI10'].values
s10_5 = bd5['DJI10'].values


window_size = 256  # size of the sliding window
hop_size = window_size // 2  # step size for the sliding window
nfft = 512  # number of FFT points

window = np.hanning(window_size)

frequencies, times, spectrogram = [], [], []

for start in range(0, len(s10_5) - window_size, hop_size):
    segment = s10_5[start:start + window_size] * window
    spectrum = np.fft.fft(segment, n=nfft)
    squared_magnitude = np.abs(spectrum) ** 2
    frequencies.append(np.fft.fftfreq(nfft))
    times.append(start)
    spectrogram.append(squared_magnitude)

frequencies = np.array(frequencies)
times = np.array(times)
spectrogram = np.array(spectrogram)

In [131]:
sampling_rate = 20000000000 * 6.59E-06
energy_trajectory = np.max(spectrogram, axis=1)
normalized_energy_trajectory = (energy_trajectory - np.mean(energy_trajectory)) / np.std(energy_trajectory)
times_in_microseconds = (times / sampling_rate) * 1e6

delta_mean = np.diff(normalized_energy_trajectory)
delta_variance = np.diff(np.square(normalized_energy_trajectory))

index_of_max_change = np.argmax(np.abs(delta_mean))

from scipy.stats import skew, kurtosis
energy_transient = normalized_energy_trajectory[index_of_max_change:]
mean_energy_transient = np.mean(energy_transient)
std_energy_transient = np.std(energy_transient)
variance_energy_transient = std_energy_transient ** 2
skewness_energy_transient = skew(energy_transient)
kurtosis_energy_transient = kurtosis(energy_transient)

In [132]:
def extract_features(energy_transient):
    mean_energy_transient = np.mean(energy_transient)
    std_energy_transient = np.std(energy_transient)
    variance_energy_transient = std_energy_transient ** 2
    skewness_energy_transient = skew(energy_transient)
    kurtosis_energy_transient = kurtosis(energy_transient)
    
    p = np.abs(np.fft.fft(energy_transient)) ** 2
    p = p / np.sum(p)  
    energy_spectral_entropy = -np.sum(p * np.log2(p))
    
    return {
        'Mean': mean_energy_transient,
        'Variance': variance_energy_transient,
        'Skewness': skewness_energy_transient,
        'Kurtosis': kurtosis_energy_transient,
        'Energy Spectral Entropy': energy_spectral_entropy
    }

drones_features = {}
features = extract_features(energy_transient)
drones_features["DJI1"] = features

feature_names = ['Mean', 'Variance', 'Skewness', 'Kurtosis', 'Energy Spectral Entropy']

for i, feature in enumerate(feature_names):
    values = [drones_features[drone][feature] for drone in drones_features]

In [133]:
for drone in drones_features:
    print("DJI10")
    for feature in drones_features[drone]:
        print(f"{feature}: {drones_features[drone][feature]}")
    print("\n")

DJI10
Mean: 1.826027060022352
Variance: 0.01979517580111779
Skewness: -5.652368908317929
Kurtosis: 39.13527949408783
Energy Spectral Entropy: 0.09109274038992779




In [134]:
output = """
DJI10
Mean: 1.826027060022352
Variance: 0.01979517580111779
Skewness: -5.652368908317929
Kurtosis: 39.13527949408783
Energy Spectral Entropy: 0.09109274038992779
"""

with open('DJI10_5.txt', 'w') as f:
    f.write(output)

In [141]:
def parse_data(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        
    drone_data = []
    drone = {}
    
    for line in lines:
        line = line.strip()
        
        if line == "":
            if drone:
                drone_data.append(drone)
            drone = {}
            continue
        
        if ':' not in line:
            drone['Drone_Type'] = line
        else:
            key, value = line.split(':')
            drone[key.strip()] = float(value.strip())
    
    if drone:
        drone_data.append(drone)
    
    return drone_data

filenames = ['DJI1_1.txt', 'DJI1_2.txt', 'DJI1_3.txt', 'DJI1_4.txt', 'DJI1_5.txt','DJI2_1.txt', 'DJI2_2.txt', 'DJI2_3.txt', 'DJI2_4.txt', 'DJI2_5.txt', 'DJI3_1.txt', 'DJI3_2.txt', 'DJI3_3.txt', 'DJI3_4.txt', 'DJI3_5.txt', 'DJI4_1.txt', 'DJI4_2.txt', 'DJI4_3.txt', 'DJI4_4.txt', 'DJI4_5.txt', 'DJI5_1.txt', 'DJI5_2.txt', 'DJI5_3.txt', 'DJI5_4.txt', 'DJI5_5.txt', 'DJI10_1.txt', 'DJI10_2.txt', 'DJI10_3.txt', 'DJI10_4.txt', 'DJI10_5.txt'] 

drone_data = []

for filename in filenames:
    drone_data.extend(parse_data(filename))  

df = pd.DataFrame(drone_data)

In [142]:
print(df)

   Drone_Type      Mean  Variance  Skewness   Kurtosis  \
0        DJI1  0.650912  1.454102  1.405409   1.923051   
1        DJI1  0.665873  1.489457  1.390628   1.805569   
2        DJI1  0.520961  0.996282  0.995916   0.381053   
3        DJI1  0.675428  1.537935  1.391658   1.728464   
4        DJI1  0.686671  1.530232  1.346617   1.563169   
5        DJI2  0.513966  1.035951  1.043501   0.490404   
6        DJI2  0.492616  0.970754  1.016147   0.454097   
7        DJI2  0.660686  1.534476  1.423478   1.867594   
8        DJI2  0.656680  1.519614  1.432043   1.914135   
9        DJI2  0.677586  1.545855  1.375302   1.682574   
10       DJI3  0.549762  1.380073  1.449958   2.200981   
11       DJI3  0.539891  1.375567  1.487771   2.348156   
12       DJI3  0.397466  0.883138  1.006411   0.507593   
13       DJI3  0.532699  1.364809  1.522294   2.508885   
14       DJI3  0.408252  0.897830  0.980915   0.382206   
15       DJI4  0.655750  1.564364  1.422976   1.817063   
16       DJI4 

In [150]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

feature_names = ['Mean', 'Variance', 'Skewness', 'Kurtosis', 'Energy Spectral Entropy']

X = df[feature_names]
y = df['Drone_Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Accuracy Score: ", accuracy_score(y_test, y_pred))


Confusion Matrix: 
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]
Accuracy Score:  0.8333333333333334
