In [1]:
import numpy as np
import pandas as pd

In [2]:
file = 'C:/Users/singh/Downloads/smol5_has5cropped.csv'
data = pd.read_csv(file)

# print(data)

In [3]:
bd = np.transpose(data)
bd = bd.drop(index='Make')
bd = bd.drop(index='RawData')
bd = bd.drop(index='NumSamples')
bd = bd.drop(index='Duration')
bd = bd.drop(index='Fs')
bd = bd.drop(index='Features')
bd = bd.drop(index='ScaleFactor')
bd = bd.drop(index='Model')
bd = bd.drop(index='Index')

In [4]:
print(bd)

                        0      1      2      3      4     5     6     7   \
CroppedData_1          310     22    390   -116    221   291   -82    87   
CroppedData_2          206    -70    374    140    209   107  -110   143   
CroppedData_3          -26    -26     50    272     57  -137  -202   211   
CroppedData_4         -186    -26    -66    228   -147  -253  -214   123   
CroppedData_5          -18   -102    118    220   -279  -301     2    -9   
...                    ...    ...    ...    ...    ...   ...   ...   ...   
CroppedData_999997   -4194  -4734  -3946  -3792  -5023     7   -70  -405   
CroppedData_999998   -1882  -2402  -1594  -1944  -3019  -305  -338  -493   
CroppedData_999999    1462   1458   1650    948    697  -849  -250  -265   
CroppedData_1000000   3894   4086   3674   3108   3901  -861   -70   211   
CroppedData_1000001   3862   4054   3462   3700   4697  -269   130   399   

                        8     9   ...     75      76      77      78      79  \
Cropped

In [5]:
print(bd.columns)

RangeIndex(start=0, stop=85, step=1)


In [6]:
bd1= bd[bd.columns[::5]]
bd2 = bd[bd.columns[1::5]]
bd3 = bd[bd.columns[2::5]]
bd4 = bd[bd.columns[3::5]]
bd5 = bd[bd.columns[4::5]]

print(bd5)

                        4     9      14     19      24     29     34     39  \
CroppedData_1          221   282      0    -15     167    -53     55    118   
CroppedData_2          209    -6     40    -95      75   -121    -29    178   
CroppedData_3           57  -130    -44   -227     -57   -145   -141     38   
CroppedData_4         -147   -46   -292   -107      19   -157   -121   -270   
CroppedData_5         -279   -38   -272    113     159     47     11   -298   
...                    ...   ...    ...    ...     ...    ...    ...    ...   
CroppedData_999997   -5023  -302  -8284  -1303  -18793   9043   3715   4370   
CroppedData_999998   -3019   -54   -600  -2211  -10709   3275   2119   8470   
CroppedData_999999     697   326   7184  -2079    2971  -4097   -853   7906   
CroppedData_1000000   3901   654  10964   -847   14711  -8965  -3309   2590   
CroppedData_1000001   4697   562   8692    949   18587  -8861  -3401  -4538   

                        44      49     54      59  

In [7]:
column_names = ['DJI1', 'DJI2', 'DJI3', 'DJI4', 'DJI5', 'DJI6','DJI7', 'DJI8', 'DJI9', 'DJI10', 'DJI11', 'DJI12', 'DJI13', 'DJI14', 'DJI15', 'DJI16', 'DJI17']
bd1.columns = column_names
bd2.columns = column_names
bd3.columns = column_names
bd4.columns = column_names
bd5.columns = column_names

In [8]:
print(bd1)

                      DJI1  DJI2    DJI3   DJI4    DJI5   DJI6  DJI7  DJI8  \
CroppedData_1          310   291      -9    288   -1054    274  -220   200   
CroppedData_2          206   107      27    584    -602     18    -8   164   
CroppedData_3          -26  -137     391    460     -22     78    52  -172   
CroppedData_4         -186  -253     463     24     -90    282    64  -240   
CroppedData_5          -18  -301     107    -60      30    218   164   -24   
...                    ...   ...     ...    ...     ...    ...   ...   ...   
CroppedData_999997   -4194     7  -10153   -516  -19994  -3982  -424  -476   
CroppedData_999998   -1882  -305  -10213  -1596  -14502   -142  1824  6244   
CroppedData_999999    1462  -849   -4825  -1676    1594   3774  2872  9124   
CroppedData_1000000   3894  -861    2875   -812   13394   5550  2380  6568   
CroppedData_1000001   3862  -269    9399    356   16506   4370   684   432   

                      DJI9   DJI10  DJI11   DJI12  DJI13   DJI1

In [293]:
import matplotlib.pyplot as plt
s9_1 = bd1['DJI9'].values
s9_2 = bd2['DJI9'].values
s9_3 = bd3['DJI9'].values
s9_4 = bd4['DJI9'].values
s9_5 = bd5['DJI9'].values


window_size = 256  
hop_size = window_size // 2  
nfft = 512  

window = np.hanning(window_size)

frequencies, times, spectrogram = [], [], []

for start in range(0, len(s9_5) - window_size, hop_size):
    segment = s9_5[start:start + window_size] * window
    spectrum = np.fft.fft(segment, n=nfft)
    squared_magnitude = np.abs(spectrum) ** 2
    frequencies.append(np.fft.fftfreq(nfft))
    times.append(start)
    spectrogram.append(squared_magnitude)

frequencies = np.array(frequencies)
times = np.array(times)
spectrogram = np.array(spectrogram)

In [294]:
sampling_rate = 20000000000 * 6.59E-06
energy_trajectory = np.max(spectrogram, axis=1)
normalized_energy_trajectory = (energy_trajectory - np.mean(energy_trajectory)) / np.std(energy_trajectory)
times_in_microseconds = (times / sampling_rate) * 1e6

delta_mean = np.diff(normalized_energy_trajectory)
delta_variance = np.diff(np.square(normalized_energy_trajectory))

index_of_max_change = np.argmax(np.abs(delta_mean))

from scipy.stats import skew, kurtosis
energy_transient = normalized_energy_trajectory[index_of_max_change:]
mean_energy_transient = np.mean(energy_transient)
std_energy_transient = np.std(energy_transient)
variance_energy_transient = std_energy_transient ** 2
skewness_energy_transient = skew(energy_transient)
kurtosis_energy_transient = kurtosis(energy_transient)

In [295]:
def extract_features(energy_transient):
    mean_energy_transient = np.mean(energy_transient)
    std_energy_transient = np.std(energy_transient)
    variance_energy_transient = std_energy_transient ** 2
    skewness_energy_transient = skew(energy_transient)
    kurtosis_energy_transient = kurtosis(energy_transient)
    
    p = np.abs(np.fft.fft(energy_transient)) ** 2
    p = p / np.sum(p)  
    energy_spectral_entropy = -np.sum(p * np.log2(p))
    
    return {
        'Mean': mean_energy_transient,
        'Variance': variance_energy_transient,
        'Skewness': skewness_energy_transient,
        'Kurtosis': kurtosis_energy_transient,
        'Energy Spectral Entropy': energy_spectral_entropy
    }

drones_features = {}
features = extract_features(energy_transient)
drones_features["DJI13"] = features

feature_names = ['Mean', 'Variance', 'Skewness', 'Kurtosis', 'Energy Spectral Entropy']

for i, feature in enumerate(feature_names):
    values = [drones_features[drone][feature] for drone in drones_features]

In [296]:
for drone in drones_features:
    print("DJI9")
    for feature in drones_features[drone]:
        print(f"{feature}: {drones_features[drone][feature]}")
    print("\n")

DJI9
Mean: 0.9989968058367322
Variance: 0.0014328816657677092
Skewness: -7.860456773055267
Kurtosis: 233.16617117210006
Energy Spectral Entropy: 0.02764284917561613




In [297]:
output = """
DJI9
Mean: 0.9989968058367322
Variance: 0.0014328816657677092
Skewness: -7.860456773055267
Kurtosis: 233.16617117210006
Energy Spectral Entropy: 0.02764284917561613
"""

with open('DJI9_5.txt', 'w') as f:
    f.write(output)

In [298]:
def parse_data(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        
    drone_data = []
    drone = {}
    
    for line in lines:
        line = line.strip()
        
        if line == "":
            if drone:
                drone_data.append(drone)
            drone = {}
            continue
        
        if ':' not in line:
            drone['Drone_Type'] = line
        else:
            key, value = line.split(':')
            drone[key.strip()] = float(value.strip())
    
    if drone:
        drone_data.append(drone)
    
    return drone_data

filenames = ['DJI1_1.txt', 'DJI1_2.txt', 'DJI1_3.txt', 'DJI1_4.txt', 'DJI1_5.txt','DJI2_1.txt', 'DJI2_2.txt', 'DJI2_3.txt', 'DJI2_4.txt', 'DJI2_5.txt', 'DJI3_1.txt', 'DJI3_2.txt', 'DJI3_3.txt', 'DJI3_4.txt', 'DJI3_5.txt', 'DJI4_1.txt', 'DJI4_2.txt', 'DJI4_3.txt', 'DJI4_4.txt', 'DJI4_5.txt', 'DJI5_1.txt', 'DJI5_2.txt', 'DJI5_3.txt', 'DJI5_4.txt', 'DJI5_5.txt', 'DJI10_1.txt', 'DJI10_2.txt', 'DJI10_3.txt', 'DJI10_4.txt', 'DJI10_5.txt', 'DJI11_1.txt', 'DJI11_2.txt', 'DJI11_3.txt', 'DJI11_4.txt', 'DJI11_5.txt','DJI12_1.txt', 'DJI12_2.txt', 'DJI12_3.txt', 'DJI12_4.txt', 'DJI12_5.txt', 'DJI13_1.txt', 'DJI13_2.txt', 'DJI13_3.txt', 'DJI13_4.txt', 'DJI13_5.txt', 'DJI14_1.txt', 'DJI14_2.txt', 'DJI14_3.txt', 'DJI14_4.txt', 'DJI14_5.txt', 'DJI5_1.txt', 'DJI15_2.txt', 'DJI15_3.txt', 'DJI15_4.txt', 'DJI15_5.txt', 'DJI16_1.txt', 'DJI16_2.txt', 'DJI16_3.txt', 'DJI16_4.txt', 'DJI16_5.txt', 'DJI17_1.txt', 'DJI17_2.txt', 'DJI17_3.txt', 'DJI17_4.txt', 'DJI17_5.txt', 'DJI6_1.txt', 'DJI6_2.txt', 'DJI6_3.txt', 'DJI6_4.txt', 'DJI6_5.txt', 'DJI7_1.txt', 'DJI7_2.txt', 'DJI7_3.txt', 'DJI7_4.txt', 'DJI7_5.txt', 'DJI8_1.txt', 'DJI8_2.txt', 'DJI8_3.txt', 'DJI8_4.txt', 'DJI8_5.txt', 'DJI9_1.txt', 'DJI9_2.txt', 'DJI9_3.txt', 'DJI9_4.txt', 'DJI9_5.txt'] 

drone_data = []

for filename in filenames:
    drone_data.extend(parse_data(filename))  

df = pd.DataFrame(drone_data)

In [299]:
print(df)

   Drone_Type      Mean  Variance  Skewness    Kurtosis  \
0        DJI1  0.650912  1.454102  1.405409    1.923051   
1        DJI1  0.665873  1.489457  1.390628    1.805569   
2        DJI1  0.520961  0.996282  0.995916    0.381053   
3        DJI1  0.675428  1.537935  1.391658    1.728464   
4        DJI1  0.686671  1.530232  1.346617    1.563169   
..        ...       ...       ...       ...         ...   
80       DJI9  0.938929  0.001206 -6.509500  186.717382   
81       DJI9  0.881766  0.001213 -6.255226  181.079135   
82       DJI9  0.467303  0.002117 -7.343324  249.222844   
83       DJI9  0.678517  0.001361 -8.435887  286.455390   
84       DJI9  0.998997  0.001433 -7.860457  233.166171   

    Energy Spectral Entropy  
0                  4.453173  
1                  4.367787  
2                  4.280684  
3                  4.264866  
4                  4.194821  
..                      ...  
80                 0.026422  
81                 0.029460  
82                 0.

In [300]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

feature_names = ['Mean', 'Variance', 'Skewness', 'Kurtosis', 'Energy Spectral Entropy']

X = df[feature_names]
y = df['Drone_Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Accuracy Score: ", accuracy_score(y_test, y_pred))


Confusion Matrix: 
 [[2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
Accuracy Score:  0.8823529411764706
